version: "2"

run:
  tests: true

linters:
  default: none
  enable:
    - depguard
    - errcheck
    - govet
    - ineffassign
    - staticcheck

linters-settings:
  depguard:
    rules:
      no-cmd-imports:
        files:
          - "!cmd/**"
        deny:
          - pkg: github.com/vncsmyrnk/underscore/cmd
            desc: command entry points must only be referenced from composition roots
